FROM mcr.microsoft.com/vscode/devcontainers/python:3.8

COPY dockerfiles/devcontainers/python/requirements.txt /tmp/
RUN set -ex; \
    pip3 --no-cache-dir install --requirement /tmp/requirements.txt

RUN python -m spacy download en_core_web_sm