version: '3'
services:

  devcontainer-python:
    image: python-cont
    build:
      context: ../..
      dockerfile: ./dockerfiles/devcontainers/python/dockerfile
    volumes:
      - ../..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      PYTHONPATH: /workspace/src:/workspace
    links:
      - webui
    depends_on:
      - mongo
      - api

  api:
    image: info-extract-api
    build:
      context: ../..
      dockerfile: ./dockerfiles/prod/api/Dockerfile
    ports:
      - 8001:8001
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017
      - PORT=8001
      - DATASET=${DATASET}
      - LOAD_COMMAND_ARGS=${LOAD_COMMAND_ARGS}
    depends_on:
      - mongo

  webui:
    image: info-extract-webui
    build:
      context: ../..
      dockerfile: ./dockerfiles/prod/webui/Dockerfile
    ports:
      - 8082:8080
    depends_on:
      - mongo
      - api

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
