const data = [
    {
      text: 'Currency',
      backText: 'currency',
      id: 0,
      suffixKey: 'c',
      backgroundColor: '#B7C985',
      textColor: '#000000',
    },
    {
      text: 'Symbol',
      backText: 'stock_symbol',
      id: 1,
      suffixKey: 's',
      backgroundColor: '#4E757C',
      textColor: '#000000',
    },
    {
      text: 'Company Name',
      backText: 'company_name',
      id: 3,
      suffixKey: 'n',
      backgroundColor: '#86A1A6',
      textColor: '#000000',
    },
    {
      text: 'Security Description',
      backText: 'security_description',
      id: 4,
      suffixKey: 'd',
      backgroundColor: '#8fcfdb',
      textColor: '#000000',
    },
    {
      text: 'Type',
      backText: 'type',
      id: 5,
      suffixKey: 'y',
      backgroundColor: '#8DA88B',
      textColor: '#000000',
    },
    {
      text: 'Frequency',
      backText: 'frequency',
      id: 6,
      suffixKey: 'f',
      backgroundColor: '#FF7A7A',
      textColor: '#000000',
    },
    {
      text: 'Announcement Date',
      backText: 'announcement_date',
      id: 7,
      suffixKey: 'a',
      backgroundColor: '#BA8479',
      textColor: '#000000',
    },
    {
      text: 'Record Date',
      backText: 'record_date',
      id: 8,
      suffixKey: 'r',
      backgroundColor: '#DBB088',
      textColor: '#000000',
    },
    {
      text: 'Ex Date',
      backText: 'ex_date',
      id: 9,
      suffixKey: 'x',
      backgroundColor: '#DEC265',
      textColor: '#000000',
    },
    {
      text: 'Payment Date',
      backText: 'payment_date',
      id: 10,
      suffixKey: 'p',
      backgroundColor: '#E97D68',
      textColor: '#000000',
    },
    {
      text: 'Per Share Amount',
      backText: 'per_share_amount',
      id: 11,
      suffixKey: 'o',
      backgroundColor: '#0C6B7C',
      textColor: '#000000',
    },
  ]
export default data;